// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// LoginRecordsColumns holds the columns for the "login_records" table.
	LoginRecordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "user_id", Type: field.TypeUUID},
		{Name: "app_id", Type: field.TypeUUID},
		{Name: "login_time", Type: field.TypeUint32},
		{Name: "ip", Type: field.TypeString},
		{Name: "location", Type: field.TypeString},
		{Name: "lat", Type: field.TypeFloat64},
		{Name: "lon", Type: field.TypeFloat64},
		{Name: "timezone", Type: field.TypeString},
	}
	// LoginRecordsTable holds the schema information for the "login_records" table.
	LoginRecordsTable = &schema.Table{
		Name:       "login_records",
		Columns:    LoginRecordsColumns,
		PrimaryKey: []*schema.Column{LoginRecordsColumns[0]},
	}
	// ProvidersColumns holds the columns for the "providers" table.
	ProvidersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "provider_name", Type: field.TypeString},
		{Name: "client_id", Type: field.TypeString, Unique: true},
		{Name: "client_secret", Type: field.TypeString, Unique: true},
		{Name: "provider_url", Type: field.TypeString},
		{Name: "provider_logo", Type: field.TypeString},
		{Name: "create_at", Type: field.TypeUint32},
		{Name: "update_at", Type: field.TypeUint32},
		{Name: "delete_at", Type: field.TypeUint32},
	}
	// ProvidersTable holds the schema information for the "providers" table.
	ProvidersTable = &schema.Table{
		Name:       "providers",
		Columns:    ProvidersColumns,
		PrimaryKey: []*schema.Column{ProvidersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LoginRecordsTable,
		ProvidersTable,
	}
)

func init() {
}
