// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/NpoolPlatform/login-door/pkg/db/ent/loginrecord"
	"github.com/NpoolPlatform/login-door/pkg/db/ent/predicate"
	"github.com/google/uuid"
)

// LoginRecordQuery is the builder for querying LoginRecord entities.
type LoginRecordQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.LoginRecord
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the LoginRecordQuery builder.
func (lrq *LoginRecordQuery) Where(ps ...predicate.LoginRecord) *LoginRecordQuery {
	lrq.predicates = append(lrq.predicates, ps...)
	return lrq
}

// Limit adds a limit step to the query.
func (lrq *LoginRecordQuery) Limit(limit int) *LoginRecordQuery {
	lrq.limit = &limit
	return lrq
}

// Offset adds an offset step to the query.
func (lrq *LoginRecordQuery) Offset(offset int) *LoginRecordQuery {
	lrq.offset = &offset
	return lrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (lrq *LoginRecordQuery) Unique(unique bool) *LoginRecordQuery {
	lrq.unique = &unique
	return lrq
}

// Order adds an order step to the query.
func (lrq *LoginRecordQuery) Order(o ...OrderFunc) *LoginRecordQuery {
	lrq.order = append(lrq.order, o...)
	return lrq
}

// First returns the first LoginRecord entity from the query.
// Returns a *NotFoundError when no LoginRecord was found.
func (lrq *LoginRecordQuery) First(ctx context.Context) (*LoginRecord, error) {
	nodes, err := lrq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{loginrecord.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (lrq *LoginRecordQuery) FirstX(ctx context.Context) *LoginRecord {
	node, err := lrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first LoginRecord ID from the query.
// Returns a *NotFoundError when no LoginRecord ID was found.
func (lrq *LoginRecordQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = lrq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{loginrecord.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (lrq *LoginRecordQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := lrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single LoginRecord entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one LoginRecord entity is not found.
// Returns a *NotFoundError when no LoginRecord entities are found.
func (lrq *LoginRecordQuery) Only(ctx context.Context) (*LoginRecord, error) {
	nodes, err := lrq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{loginrecord.Label}
	default:
		return nil, &NotSingularError{loginrecord.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (lrq *LoginRecordQuery) OnlyX(ctx context.Context) *LoginRecord {
	node, err := lrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only LoginRecord ID in the query.
// Returns a *NotSingularError when exactly one LoginRecord ID is not found.
// Returns a *NotFoundError when no entities are found.
func (lrq *LoginRecordQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = lrq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{loginrecord.Label}
	default:
		err = &NotSingularError{loginrecord.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (lrq *LoginRecordQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := lrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of LoginRecords.
func (lrq *LoginRecordQuery) All(ctx context.Context) ([]*LoginRecord, error) {
	if err := lrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return lrq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (lrq *LoginRecordQuery) AllX(ctx context.Context) []*LoginRecord {
	nodes, err := lrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of LoginRecord IDs.
func (lrq *LoginRecordQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := lrq.Select(loginrecord.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (lrq *LoginRecordQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := lrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (lrq *LoginRecordQuery) Count(ctx context.Context) (int, error) {
	if err := lrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return lrq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (lrq *LoginRecordQuery) CountX(ctx context.Context) int {
	count, err := lrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (lrq *LoginRecordQuery) Exist(ctx context.Context) (bool, error) {
	if err := lrq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return lrq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (lrq *LoginRecordQuery) ExistX(ctx context.Context) bool {
	exist, err := lrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the LoginRecordQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (lrq *LoginRecordQuery) Clone() *LoginRecordQuery {
	if lrq == nil {
		return nil
	}
	return &LoginRecordQuery{
		config:     lrq.config,
		limit:      lrq.limit,
		offset:     lrq.offset,
		order:      append([]OrderFunc{}, lrq.order...),
		predicates: append([]predicate.LoginRecord{}, lrq.predicates...),
		// clone intermediate query.
		sql:  lrq.sql.Clone(),
		path: lrq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.LoginRecord.Query().
//		GroupBy(loginrecord.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (lrq *LoginRecordQuery) GroupBy(field string, fields ...string) *LoginRecordGroupBy {
	group := &LoginRecordGroupBy{config: lrq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := lrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return lrq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID uuid.UUID `json:"user_id,omitempty"`
//	}
//
//	client.LoginRecord.Query().
//		Select(loginrecord.FieldUserID).
//		Scan(ctx, &v)
//
func (lrq *LoginRecordQuery) Select(fields ...string) *LoginRecordSelect {
	lrq.fields = append(lrq.fields, fields...)
	return &LoginRecordSelect{LoginRecordQuery: lrq}
}

func (lrq *LoginRecordQuery) prepareQuery(ctx context.Context) error {
	for _, f := range lrq.fields {
		if !loginrecord.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if lrq.path != nil {
		prev, err := lrq.path(ctx)
		if err != nil {
			return err
		}
		lrq.sql = prev
	}
	return nil
}

func (lrq *LoginRecordQuery) sqlAll(ctx context.Context) ([]*LoginRecord, error) {
	var (
		nodes = []*LoginRecord{}
		_spec = lrq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &LoginRecord{config: lrq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, lrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (lrq *LoginRecordQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := lrq.querySpec()
	return sqlgraph.CountNodes(ctx, lrq.driver, _spec)
}

func (lrq *LoginRecordQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := lrq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (lrq *LoginRecordQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   loginrecord.Table,
			Columns: loginrecord.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: loginrecord.FieldID,
			},
		},
		From:   lrq.sql,
		Unique: true,
	}
	if unique := lrq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := lrq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, loginrecord.FieldID)
		for i := range fields {
			if fields[i] != loginrecord.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := lrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := lrq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := lrq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := lrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (lrq *LoginRecordQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(lrq.driver.Dialect())
	t1 := builder.Table(loginrecord.Table)
	columns := lrq.fields
	if len(columns) == 0 {
		columns = loginrecord.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if lrq.sql != nil {
		selector = lrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range lrq.predicates {
		p(selector)
	}
	for _, p := range lrq.order {
		p(selector)
	}
	if offset := lrq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := lrq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// LoginRecordGroupBy is the group-by builder for LoginRecord entities.
type LoginRecordGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (lrgb *LoginRecordGroupBy) Aggregate(fns ...AggregateFunc) *LoginRecordGroupBy {
	lrgb.fns = append(lrgb.fns, fns...)
	return lrgb
}

// Scan applies the group-by query and scans the result into the given value.
func (lrgb *LoginRecordGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := lrgb.path(ctx)
	if err != nil {
		return err
	}
	lrgb.sql = query
	return lrgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (lrgb *LoginRecordGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := lrgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (lrgb *LoginRecordGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(lrgb.fields) > 1 {
		return nil, errors.New("ent: LoginRecordGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := lrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (lrgb *LoginRecordGroupBy) StringsX(ctx context.Context) []string {
	v, err := lrgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lrgb *LoginRecordGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = lrgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{loginrecord.Label}
	default:
		err = fmt.Errorf("ent: LoginRecordGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (lrgb *LoginRecordGroupBy) StringX(ctx context.Context) string {
	v, err := lrgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (lrgb *LoginRecordGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(lrgb.fields) > 1 {
		return nil, errors.New("ent: LoginRecordGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := lrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (lrgb *LoginRecordGroupBy) IntsX(ctx context.Context) []int {
	v, err := lrgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lrgb *LoginRecordGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = lrgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{loginrecord.Label}
	default:
		err = fmt.Errorf("ent: LoginRecordGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (lrgb *LoginRecordGroupBy) IntX(ctx context.Context) int {
	v, err := lrgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (lrgb *LoginRecordGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(lrgb.fields) > 1 {
		return nil, errors.New("ent: LoginRecordGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := lrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (lrgb *LoginRecordGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := lrgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lrgb *LoginRecordGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = lrgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{loginrecord.Label}
	default:
		err = fmt.Errorf("ent: LoginRecordGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (lrgb *LoginRecordGroupBy) Float64X(ctx context.Context) float64 {
	v, err := lrgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (lrgb *LoginRecordGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(lrgb.fields) > 1 {
		return nil, errors.New("ent: LoginRecordGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := lrgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (lrgb *LoginRecordGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := lrgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (lrgb *LoginRecordGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = lrgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{loginrecord.Label}
	default:
		err = fmt.Errorf("ent: LoginRecordGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (lrgb *LoginRecordGroupBy) BoolX(ctx context.Context) bool {
	v, err := lrgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (lrgb *LoginRecordGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range lrgb.fields {
		if !loginrecord.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := lrgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := lrgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (lrgb *LoginRecordGroupBy) sqlQuery() *sql.Selector {
	selector := lrgb.sql.Select()
	aggregation := make([]string, 0, len(lrgb.fns))
	for _, fn := range lrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(lrgb.fields)+len(lrgb.fns))
		for _, f := range lrgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(lrgb.fields...)...)
}

// LoginRecordSelect is the builder for selecting fields of LoginRecord entities.
type LoginRecordSelect struct {
	*LoginRecordQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (lrs *LoginRecordSelect) Scan(ctx context.Context, v interface{}) error {
	if err := lrs.prepareQuery(ctx); err != nil {
		return err
	}
	lrs.sql = lrs.LoginRecordQuery.sqlQuery(ctx)
	return lrs.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (lrs *LoginRecordSelect) ScanX(ctx context.Context, v interface{}) {
	if err := lrs.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (lrs *LoginRecordSelect) Strings(ctx context.Context) ([]string, error) {
	if len(lrs.fields) > 1 {
		return nil, errors.New("ent: LoginRecordSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := lrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (lrs *LoginRecordSelect) StringsX(ctx context.Context) []string {
	v, err := lrs.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (lrs *LoginRecordSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = lrs.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{loginrecord.Label}
	default:
		err = fmt.Errorf("ent: LoginRecordSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (lrs *LoginRecordSelect) StringX(ctx context.Context) string {
	v, err := lrs.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (lrs *LoginRecordSelect) Ints(ctx context.Context) ([]int, error) {
	if len(lrs.fields) > 1 {
		return nil, errors.New("ent: LoginRecordSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := lrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (lrs *LoginRecordSelect) IntsX(ctx context.Context) []int {
	v, err := lrs.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (lrs *LoginRecordSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = lrs.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{loginrecord.Label}
	default:
		err = fmt.Errorf("ent: LoginRecordSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (lrs *LoginRecordSelect) IntX(ctx context.Context) int {
	v, err := lrs.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (lrs *LoginRecordSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(lrs.fields) > 1 {
		return nil, errors.New("ent: LoginRecordSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := lrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (lrs *LoginRecordSelect) Float64sX(ctx context.Context) []float64 {
	v, err := lrs.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (lrs *LoginRecordSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = lrs.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{loginrecord.Label}
	default:
		err = fmt.Errorf("ent: LoginRecordSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (lrs *LoginRecordSelect) Float64X(ctx context.Context) float64 {
	v, err := lrs.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (lrs *LoginRecordSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(lrs.fields) > 1 {
		return nil, errors.New("ent: LoginRecordSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := lrs.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (lrs *LoginRecordSelect) BoolsX(ctx context.Context) []bool {
	v, err := lrs.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (lrs *LoginRecordSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = lrs.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{loginrecord.Label}
	default:
		err = fmt.Errorf("ent: LoginRecordSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (lrs *LoginRecordSelect) BoolX(ctx context.Context) bool {
	v, err := lrs.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (lrs *LoginRecordSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := lrs.sql.Query()
	if err := lrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
