apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-door
  namespace: kube-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login-door
  template:
    metadata:
      labels:
        app: login-door
    spec:
      containers:
      - name: login-door
        image: uhub.service.ucloud.cn/entropypool/login-door:latest
        imagePullPolicy: Always
        env:
        - name: ENV_ENVIRONMENT_TARGET
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.target
        - name: ENV_CONSUL_HOST
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_host
        - name: ENV_CONSUL_PORT
          valueFrom:
            configMapKeyRef:
              name: system-environment
              key: environment.consul_port
        - name: ENV_CLUSTER_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

---
apiVersion: v1
kind: Service
metadata:
  name: login-door
  namespace: kube-system
spec:
  ports:
  - name: api
    port: 50060
    targetPort: 50060
  - name: grpc
    port: 50061
    targetPort: 50061
  - name: prometheus
    port: 50062
    targetPort: 50062
  selector:
    app: login-door
