// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Provider is the predicate function for provider builders.
type Provider func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
