// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// LoginRecord is the predicate function for loginrecord builders.
type LoginRecord func(*sql.Selector)

// Provider is the predicate function for provider builders.
type Provider func(*sql.Selector)
